name: Skyblock
version: '${project.version}'
main: de.noctivag.skyblock.SkyblockPlugin
api-version: 1.21
author: Noctivag
description: Advanced Minecraft Skyblock plugin with comprehensive features and systems
folia-supported: true

commands:
  hub:
    description: Teleport to the hub
    usage: /<command>
    permission: skyblock.hub
    aliases: [lobby, spawn]
  skyblock:
    description: Main skyblock command
    usage: /<command>
    permission: skyblock.use
    aliases: [sb, sky]

permissions:
  skyblock.hub:
    description: Allows access to hub teleportation
    default: true
  skyblock.use:
    description: Allows access to skyblock commands
    default: true
  skyblock.admin:
    description: Allows access to admin commands
    default: op
