name: Skyblock
version: '${project.version}'
main: de.noctivag.skyblock.SkyblockPlugin
api-version: 1.21
author: Noctivag
description: Advanced Minecraft Skyblock plugin with comprehensive features and systems
folia-supported: true

commands:
  hub:
    description: Teleport to the hub
    usage: /<command>
    permission: skyblock.hub
    aliases: [lobby, spawn]
  skyblock:
    description: Main skyblock command
    usage: /<command>
    permission: skyblock.use
    aliases: [sb, sky]
  menu:
    description: Open the main Skyblock menu
    usage: /<command>
    permission: skyblock.menu
    aliases: [gui, m]
  trade:
    description: Trade with other players
    usage: /<command> <player> or /<command> accept <player> or /<command> deny <player>
    permission: skyblock.trade
    aliases: [t]
  arsenal:
    description: Open the arsenal menu with all plugin items (OP only)
    usage: /<command>
    permission: skyblock.arsenal
    aliases: [items, allitems]

permissions:
  skyblock.hub:
    description: Allows access to hub teleportation
    default: true
  skyblock.use:
    description: Allows access to skyblock commands
    default: true
  skyblock.menu:
    description: Allows access to the main menu
    default: true
  skyblock.trade:
    description: Allows trading with other players
    default: true
  skyblock.admin:
    description: Allows access to admin commands
    default: op
  skyblock.arsenal:
    description: Allows access to the arsenal menu with all plugin items
    default: op
