name: SkyblockMinimal
version: '${project.version}'
main: de.noctivag.skyblock.minimal.SkyblockPluginMinimal
api-version: 1.21
author: Noctivag
description: Minimal Skyblock Plugin - Working Version
folia-supported: true

commands:
  hub:
    description: Teleport to the hub
    usage: /<command>
    permission: skyblock.hub
    aliases: [lobby, spawn]

permissions:
  skyblock.hub:
    description: Allows access to hub teleportation
    default: true
